# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install:
    - brew update
    - gem install cocoapods -v '0.33.1'
    - xctool --version
    - cd Example && pod install && cd -
script:
- xctool test -workspace Example/CoreDataStackPod.xcworkspace -configuration Debug -scheme CoreDataStackPod -sdk iphonesimulator7.0 -arch i386 ONLY_ACTIVE_ARCH=NO -showTasks

