# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install:
    - brew update
    - gem install cocoapods -v '0.33.1'
    - xctool --version
    - cd Example && pod install && cd -
script:
xcodebuild -workspace CoreDataStackPod.xcworkspace -scheme CoreDataStackPod -sdk iphonesimulator -configuration Debug clean build test

